apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rss-evaluation-service-monitor
  namespace: rss-evaluation
  labels:
    app: rss-evaluation-service
    release: kube-prometheus-stack
    team: rss-evaluation-service
spec:
  selector:
    matchLabels:
      app: rss-evaluation-service
  namespaceSelector:
    matchNames: 
    - rss-evaluation
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s
